name: jurisolutions
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_messaging: ^16.0.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  cpf_cnpj_validator: ^2.0.0 # Para validar CPF e CNPJ
  intl: ^0.20.2 # Para formatação de data
  mask_text_input_formatter: ^2.9.0
  flutter_multi_formatter: ^2.13.7
  google_sign_in: ^6.2.1
  http: ^1.2.1
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  permission_handler: ^12.0.0+1
  flutter_local_notifications: ^19.4.0
  syncfusion_flutter_calendar: ^30.2.7
  timezone: ^0.10.1
  table_calendar: ^3.2.0
  package_info_plus: ^8.3.1
  ota_update: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/   # Isso inclui tudo dentro da pasta 'assets' e subpastas
    - assets/icon/  # Isso inclui tudo dentro da pasta 'assets' e subpastas

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon/splash.png"
  android: true
  ios: true
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "assets/icon/background.png"
  adaptive_icon_foreground: "assets/icon/foreground.png"
  image_path: "assets/icon/icon.png"
