// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFhl0dubrTAhziZoPNfz11wpDokkzMk5c',
    appId: '1:898076500947:web:479ed27856f346b1eb0526',
    messagingSenderId: '898076500947',
    projectId: 'jurisolutio',
    authDomain: 'jurisolutio.firebaseapp.com',
    storageBucket: 'jurisolutio.firebasestorage.app',
    measurementId: 'G-CJP9DFJJN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT6naWxdIJw5u1znXsI1HXsLldY7-OS0c',
    appId: '1:898076500947:android:b206b68c9fe8fd02eb0526',
    messagingSenderId: '898076500947',
    projectId: 'jurisolutio',
    storageBucket: 'jurisolutio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS6rapMPJ1fgs-7zOBeAUtJc2QMUT3iww',
    appId: '1:898076500947:ios:eb47bff25ce28206eb0526',
    messagingSenderId: '898076500947',
    projectId: 'jurisolutio',
    storageBucket: 'jurisolutio.firebasestorage.app',
    iosBundleId: 'com.example.jurisolutionss',
  );
}
