// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsaiAu7LXxFBelwKAo41wUmLXeVtcUQ4Y',
    appId: '1:123599106616:web:a022b1c82669a9ca34accd',
    messagingSenderId: '123599106616',
    projectId: 'jurisolutions-3ed1f',
    authDomain: 'jurisolutions-3ed1f.firebaseapp.com',
    storageBucket: 'jurisolutions-3ed1f.firebasestorage.app',
    measurementId: 'G-3W3G1VLBXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXY02sSauQVLxFcYGK5_iOverLeGcww2A',
    appId: '1:123599106616:android:1c696a030420e2b734accd',
    messagingSenderId: '123599106616',
    projectId: 'jurisolutions-3ed1f',
    storageBucket: 'jurisolutions-3ed1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcthYU6rvXpWG4CiVYI1BhSwi6IHVaHRA',
    appId: '1:123599106616:ios:241dd7dc419e41b034accd',
    messagingSenderId: '123599106616',
    projectId: 'jurisolutions-3ed1f',
    storageBucket: 'jurisolutions-3ed1f.firebasestorage.app',
    iosBundleId: 'com.example.jurisolutions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcthYU6rvXpWG4CiVYI1BhSwi6IHVaHRA',
    appId: '1:123599106616:ios:241dd7dc419e41b034accd',
    messagingSenderId: '123599106616',
    projectId: 'jurisolutions-3ed1f',
    storageBucket: 'jurisolutions-3ed1f.firebasestorage.app',
    iosBundleId: 'com.example.jurisolutions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsaiAu7LXxFBelwKAo41wUmLXeVtcUQ4Y',
    appId: '1:123599106616:web:d35862b013fa8a0334accd',
    messagingSenderId: '123599106616',
    projectId: 'jurisolutions-3ed1f',
    authDomain: 'jurisolutions-3ed1f.firebaseapp.com',
    storageBucket: 'jurisolutions-3ed1f.firebasestorage.app',
    measurementId: 'G-DFNF0RQRDZ',
  );

}